### ISSUE TITLE
Improve testing to cover api fn calls

### ISSUE THREAD

**Issue by ftikbogle** [fti-technology/node-skytap#11]
In order to resolve some open issues with confidence in not breaking the library, we need to instrument the api call parts of the library with tests.

See issues: https://github.com/fti-technology/node-skytap/issues/9, https://github.com/fti-technology/node-skytap/issues/5, https://github.com/fti-technology/node-skytap/issues/12

I suggest we use [nock](https://github.com/pgte/nock), as we can test our api calls without modifying library code by hooking into node's http lib directly.

See a sample change here: https://github.com/ftikbogle/node-skytap/blob/MockTests/test/skytap.js

**Comment by ftikbogle** [comment]
Added some more examples of nock tests:
https://github.com/fti-technology/node-skytap/compare/master...ftikbogle:0ffeb7e106903449d7aac0903f75e0dbfd797596

After using this a bit, I feel like this may be able to be simplified a lot. We don't really care about the content of the response, as we're just passing it directly onto the consumer. I think I'll work on another revision that simplifies these calls quite a bit.

I think we only care about:

- The requests are actually called (automatically verify with nock.done())
- The request had it's body set correctly (we can just feed these through to the api call)
- The request had it's parameters (if any) sent correctly
- There is some sort of response (but we don't care about the content)

**Comment by bmancini55** [comment]
Yeah that sounds perfect.

**Comment by ftikbogle** [comment]
Already found a bug while implementing nock tests: https://github.com/fti-technology/node-skytap/pull/13

**Comment by ftikbogle** [comment]
Work on this is ongoing in the testing branch: https://github.com/fti-technology/node-skytap/compare/master...ftikbogle:MockTests
