### ISSUE TITLE
Update documentation on extra query parameters

### ISSUE THREAD

**Issue by kaylynb** [fti-technology/node-skytap#6]
There doesn't seem to be an option to query environments in a way that doesn't reset the auto-suspend timer.

See the API docs: http://help.skytap.com/#API_Documentation.html

There are no anchors to link to in the doc, so here is the relevant portion:

> By default, this GET request will be recognized by the auto-suspend timer as activity in the environment. This means that auto-suspend will not take effect if this request is made within the auto-suspend window you have set (e.g., 5 minutes, 60 minutes, etc.). If you would like the auto-suspend timer to ignore this request and not treat it as activity, include "?keep_idle=true" in the request.

**Comment by ftikbogle** [comment]
Looks like we can already do this as the library converts unknown parameters to uri parameters:

`environments.get({ configuration_id: 1234, keep_idle: true }`

Perhaps we should update the documentation on this behavior.

**Comment by bmancini55** [comment]
Good call!  The doco should definitively cover additional parameter passing.  The `keep_idle` param is a perfect one to highlight explicitly as well.
